# Deployment Configuration
base_url: http://localhost:3000


# Feature Flags
features:
  allow_uninvited_signups: true
  allow_multiple_organizations: false
  verify_emails: false


auth:
  mode: "sso_only" # hybrid | local_only | sso_only

google_oauth:
  enabled: false

oidc_providers:
  - name: keycloak
    enabled: true
    # IMPORTANT: Use localhost:8090 for issuer URL so browser redirects work correctly
    # Keycloak will handle the internal container-to-container communication
    issuer: http://keycloak:8080/realms/kashika-ai
    client_id: kashika-ai
    client_secret: dnbm8NwQQXvpfciXHnepXzeMbL0VVduW
    scopes: ["openid", "profile", "email"]
    discovery: true
    uid_claim: sub
    end_session_endpoint: http://keycloak:8080/realms/kashika-ai/protocol/openid-connect/logout
    post_logout_redirect_uri: http://localhost:3000/users/sign-in?redirect=/catalog

encryption_key: ${BOW_ENCRYPTION_KEY}

intercom:
  enabled: false
